" Basic universal configurations
set rnu

" Syntax and highlighting
syntax enable
filetype plugin on " enables $HOME/.vim/ftplugin folder with .vim files
" for filetype confugirations

" We can source other vimrc for modularity using "source <filename>"
