" Basic universal configurations
set rnu

" Syntax and highlighting
syntax enable
filetype plugin on " enables $HOME/.vim/ftplugin folder with .vim files
" for filetype confugirations
filetype indent on

" Enable mouse support
set mouse=a

" VIM Whitespace - Added whitespaces
" Using vim plugin for better spaces; Using this for just backup
" set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣
" set nolist


" We can source other vimrc for modularity using "source <filename>"
" source $DOTS/vimconfs/NERDTree.vimrc
source ~/.plugins.vimrc/NERDTree.vimrc

" Vim Commentary Plugin; Will add to go.vim
autocmd FileType go setlocal commentstring=#\ %s

" ====== Custom Settings =======





" ======= Experimental Settings =========
inoremap kj <ESC>	" Added additional interactive mode <ESC>
vnoremap kj <ESC>	" Added additional interactive mode <ESC>
