---
- name: Custom My Applications Setup
  hosts: "localhost"
  become: yes
  become_user: kal
  tasks:
  - name: Creates directory
    file:
      path: $HOME/MyApplications/bin # MyApplications is created automatically
      state: directory
      owner: kal
      group: kal
      mode: 0775

  - name: Clone git repos
    git:
      repo: git@github.com:kpbeta/dots.git
      dest: $HOME/MyApplications/dots/
      clone: yes
      update: no  # Might not run for `dots` project if yes


