# Do environment-management bootstrap here
- hosts: ["localhost"]
  become: true
  become_user: root
  tasks:
  - name: Setup wireguard-tools
    apt:
      state: latest
      name:
        - wireguard-tools
  - name: Install tailscale
    shell:
      cmd: curl -fsSL https://tailscale.com/install.sh | sh


