# Run with `ansible-playbook <filename>`
- hosts: ["localhost"]
  become: true
  become_user: root
  tasks:
  - name: Install ssh packages
    apt:
      state: latest
      name:
        - openssh-server
